### ISSUE TITLE
Adding field buttons are broken on the submit page

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#71]
For multi-field options the [+] button is not working.

**Comment by LLTommy** [comment]
Wait, that is funny, I know that they used to work. I don't know what happened there.

**Comment by adamnovak** [comment]
The problem is that main.js is now included in the header instead of at the end of the page, so the [code to hook up the event listeners](https://github.com/arvados/bh20-seq-resource/blob/39eca644ed4a0a86510ae0b8afb8da9207d9750a/bh20simplewebuploader/static/main.js#L168-L174) runs before the elements that it is trying to attach listeners to exist.

Either the script needs to go back to the bottom of the page, or we need to use [`<script defer>`](https://www.w3schools.com/tags/att_script_defer.asp), or we need to put the hook-up code in a `DOMContentLoaded` handler.

**Comment by pjotrp** [comment]
Thanks @adamnovak - I moved the generic JS up indeed, so it is visible on loading the page. Listeners can go down.
